// <auto-generated />
namespace MovieNight.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenamedPersonIdforCastMembersDirectorsandWriters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenamedPersonIdforCastMembersDirectorsandWriters));
        
        string IMigrationMetadata.Id
        {
            get { return "201510240330151_Renamed PersonId for CastMembers, Directors, and Writers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
